version: 1.0.{build}
image: Visual Studio 2017
before_build:
    - ps: |
        nuget restore MSBuildLogOctokitChecker.sln -Verbosity Quiet
        cd ./MSBLOC.web
        npm install
build_script:
- ps: >-
    msbuild MSBuildLogOctokitChecker.sln --% /p:Configuration=Release /bl:output.binlog /verbosity:minimal
after_build:
    - cmd: dotnet publish MSBLOC.Web  --configuration Release --output %appveyor_build_folder%\dist
artifacts:
    - path: output.binlog
      name: log
      type: File
    - path: dist
      name: dist.web
      type: WebDeployPackage
