version: 1.0.{build}
image: Visual Studio 2017
before_build:
    - ps: |
        nuget restore MSBuildLogOctokitChecker.sln
build:
    project: MSBuildLogOctokitChecker.sln
    verbosity: minimal
after_build:
    - cmd: dotnet publish MSBLOC.Web --output %appveyor_build_folder%\dist
artifacts:
    - path: dist
      name: dist.web
      type: WebDeployPackage