version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install fake-cli -g
  - dotnet tool install coverlet.console -g
  - choco install --no-progress codecov -y
  - choco install --no-progress gitversion.portable -y
before_build:
  - ps: gitversion /output buildserver 
build_script:
- ps: >-
    fake run Build.fsx
test: off
artifacts:
  - path: build
    name: build.web
    type: WebDeployPackage
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: BuildCrossCheck v$(GitVersion_SemVer)
  description: 'BuildCrossCheck v$(GitVersion_SemVer)'
  auth_token:
    secure: 8wLI8hf2W3L/V5BUk/tdGDs+gWryh9Y8HxCQk9iq48xV/n+hxShodChwuHAm2DsS
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
- provider: WebDeploy
  server: https://buildcrosscheck.scm.azurewebsites.net:443/msdeploy.axd?site=BuildCrossCheck
  website: BuildCrossCheck
  username: $BuildCrossCheck
  password: $(GITHUB_TOKEN)
  aspnet_core: true
  aspnet_core_force_restart: true
  remove_files: true
  app_offline: true
  artifact: build.web
  on:
    branch: master
    appveyor_repo_tag: true