version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: |
    dotnet tool install fake-cli -g
    dotnet tool install coverlet.console -g
    choco install --no-progress codecov
build_script:
- ps: >-
    fake run Build.fsx